name: EXT Example Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  desktop-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print supported file types
        run: |
          echo "Markdown"
          echo "JSON"
          echo "YAML"
